HW#1-OOP-Khokhlov Yevhenii
Cursoreducation/Python-Enchantress pull request #2
Opened 2020-12-26 15:46 UTC by yevhenii-khokhlov

2020-12-29 10:14 UTC, dimigor requested changes

2020-12-29 10:14 UTC, dimigor commented on .idea/.gitignore
> +/workspace.xml
please, exclude all .idea files
you can create compete .gitignore file here: https://www.toptal.com/developers/gitignore

2020-12-29 10:14 UTC, dimigor commented on homework/Animals.py
> +    def set_color(self, color: str):
you can also use `property.setter`

2020-12-29 10:14 UTC, dimigor commented on homework/Animals.py
> +class Wolf(Dog, color='grey'):
`color='grey'` what does it mean?

2020-12-29 10:14 UTC, dimigor commented on homework/composition.py
> +        app3 = App('TextRedactor', 42)
create dict with values {'Chrome': 500, 'Photoshop': 4000} and in loop create instances

2020-12-29 10:14 UTC, dimigor commented on homework/metaclass.py
> +        return self
you do not need to return self

2021-01-02 07:17 UTC, yevhenii-khokhlov commented on homework/Animals.py
> +    def set_color(self, color: str):
Done

2021-01-02 07:19 UTC, yevhenii-khokhlov commented on homework/metaclass.py
> +        return self
Done

2021-01-02 07:21 UTC, yevhenii-khokhlov commented on homework/Animals.py
> +class Wolf(Dog, color='grey'):
this is my mistake, 
I deleted

2021-01-02 08:09 UTC, yevhenii-khokhlov commented on homework/composition.py
> +        app3 = App('TextRedactor', 42)
Done

2021-01-08 13:34 UTC, closed without merging